language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-bnsf' ]; then cd .. && eval "mv $currentfolder generator-bnsf" && cd generator-bnsf; fi
